# fly.toml app configuration file generated for patientorac on 2023-05-11T13:58:22+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patientorac"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "syd"
processes = []

[build]

[env]
  PORT = "3333"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3333
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.script_checks]]
    command = "/app/health_check.sh"
    grace_period = "1s"
    interval = "5s"
    restart_limit = 0

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
